# By Hashan Wijemanna
name: alpha
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  csv: ^6.0.0
  lottie: ^3.1.2
  encrypt: ^5.0.3
  oauth2: ^2.0.3
  cron: ^0.6.1
  network_info_plus: ^6.1.3
  flutter_background_service: ^5.1.0
  flutter_inappwebview: ^6.0.0-beta.22
  path_provider: ^2.1.5
  #shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.3.0

  # Encourages good practices
  flutter_lints: ^4.0.0

  # App icon generator

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/
    - assets/intro/


